{"uuid": "9a12d4d6-7310-4bd4-8958-ca578b00459e", "children": ["0bd4920b-803b-4c5e-b3a5-b051ed92cf35"], "befores": [{"name": "loginrbixac", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument\n  (Session info: chrome=114.0.5735.134)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00D5A813+48355]\n\t(No symbol) [0x00CEC4B1]\n\t(No symbol) [0x00BF5220]\n\t(No symbol) [0x00BE88E2]\n\t(No symbol) [0x00BE7138]\n\t(No symbol) [0x00BE7688]\n\t(No symbol) [0x00BF6B52]\n\t(No symbol) [0x00C4CF01]\n\t(No symbol) [0x00C3A73C]\n\t(No symbol) [0x00C4C922]\n\t(No symbol) [0x00C3A536]\n\t(No symbol) [0x00C182DC]\n\t(No symbol) [0x00C193DD]\n\tGetHandleVerifier [0x00FBAABD+2539405]\n\tGetHandleVerifier [0x00FFA78F+2800735]\n\tGetHandleVerifier [0x00FF456C+2775612]\n\tGetHandleVerifier [0x00DE51E0+616112]\n\t(No symbol) [0x00CF5F8C]\n\t(No symbol) [0x00CF2328]\n\t(No symbol) [0x00CF240B]\n\t(No symbol) [0x00CE4FF7]\n\tBaseThreadInitThunk [0x757F8484+36]\n\tRtlValidSecurityDescriptor [0x77C32FEA+282]\n\tRtlValidSecurityDescriptor [0x77C32FBA+234]\n\n", "trace": "  File \"c:\\users\\ruyu.yin\\securebrowser_autotesting\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\ruyu.yin\\securebrowser_autotesting\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\ruyu.yin\\securebrowser_autotesting\\lib\\site-packages\\_pytest\\fixtures.py\", line 909, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"E:\\catalogserviceUIautotesting\\conftest.py\", line 191, in loginrbixac\n    driver.get(url)\n  File \"c:\\users\\ruyu.yin\\securebrowser_autotesting\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"c:\\users\\ruyu.yin\\securebrowser_autotesting\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\ruyu.yin\\securebrowser_autotesting\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1687226742437, "stop": 1687226743339}], "start": 1687226742437, "stop": 1687226743480}